### ISSUE TITLE
Determine what language and framework to use for registrar backend

### ISSUE THREAD

**Issue by SSPJ** [cisagov/dotgov#12]
- [x] Draft ADR and present to CISA for sign-off
    - [x] document trade-offs
- [x] Create ~and deploy~ hello world

Deployment happens in #11 .

**Comment by colinmurphy01** [comment]
Thank you for amending the consequences with considerations for hiring and migrating. Since the decision has been accepted, is there any other review you need prior to closing?

**Comment by SSPJ** [comment]
@colinmurphy01 I would like to keep this ticket open a while longer, until a running application is deployed in our cloud.gov sandbox. Alternatively, we can move that item to #11 and close this issue.

**Comment by colinmurphy01** [comment]
Ah roger. Let's leave it open, it's unique and separate. Should the status change from review to in progress or blocked if it's dependent on #11
