### ISSUE TITLE
R1: Current state analysis (Flows) – Planning and Scheduling

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/dotgov#36]
- [x] Finish draft a [Research Plan](https://docs.google.com/document/d/10se0XGfiCo_P_s4wYFuS1l4JsCm7v1aUAL3PXy0UfU4/edit)
- [x] Review with @boonerang 
- [x] Share with team, via slack and address feedback
- [x] Identify any meetings that need to be scheduled
- [x] Schedule meetings with @h-m-f-t

**Comment by loganmeetsworld** [comment]
#32 is related

**Comment by colinmurphy01** [comment]
After discussing with @igorkorenfeld @boonerang and @michelle-rago we determined that with the creation of an initial flow document and #32 , this can be closed.

After we complete qualitative research with admins and current customers, we will then be able to amend this flow with pain points or other priority use cases for MVP consideration. That can be tracked in a separate ticket.
