### ISSUE TITLE
Meet with TTS / 10x GNS to discuss .gov use cases and feasibility

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/dotgov#5]
- [x] Meet with GNS Team, to understand each other's current state and goals
- [x] Assess feasibility of working together
- [x] Share notes in slack (internal or external)
- [x] Determine whether to move forward with a spike or looping in Cameron

_Related to #16_

**Comment by loganmeetsworld** [comment]
We met with this team to discuss the 10x, which is building on a fork of [Notify](https://notifications.service.gov.uk/). We shared with them our use case and discussed the longterm vision for the product. Next steps are evaluating our current options inside CISA for email and other notification services.

**Comment by loganmeetsworld** [comment]
I have pinged our group internally for discussion of alternatives within CISA for email. I will report any findings on this ticket.

**Comment by loganmeetsworld** [comment]
I am actually going to report findings on #16 and we can close this out.
